### PR TITLE
replaced Fatal with Lvl2 and added test

### LINKED ISSUE #159: `GenerateNaryTreeWithRoot` should not `Fatal`
Now: If the given root in `GenerateNaryTreeWithRoot` doesn't exist, it `Fatal`s.

Wanted: return `nil` if something goes wrong.

Why not return `(*Tree, error)`? - because this would break API-compatibility with `v1`.

### PR DESCRIPTION
**Pull request by ineiti**
Closes #159

### CODE REVIEW

File: tree.go [hunk 1]
```diff
@@ -474,7 +474,7 @@ func (el *Roster) GenerateBigNaryTree(N, nodes int) *Tree {
 func (el *Roster) GenerateNaryTreeWithRoot(N int, rootServerIdentity *network.ServerIdentity) *Tree {
 	rootIndex, _ := el.Search(rootServerIdentity.ID)
 	if rootIndex < 0 {
-		log.Fatal(rootServerIdentity, el.List, log.Stack())
+		log.Lvl2("Asked for non-existing root:", rootServerIdentity, el.List, log.Stack())
```
Comment (nikkolasg) [inline tree.go]: I'm Ok with not panicking but then you must return an error, don't you think ?

Comment (nikkolasg) [inline tree.go]: and the `log.Stack` has no meaning anymore.

Comment (ineiti) [inline tree.go]: I'll remove `log.Stack`, but won't add an error, as this would break `v1`-API-compatibility (as explained in the issue #159). For the moment it's: return `nil` -> it failed.
