### PR TITLE
fail if receiving-channel is full

### LINKED ISSUE #219: onet-channels block if there are too many messages waiting
In line

https://github.com/dedis/onet/blob/master/treenode.go#L168

onet blocks if the message-queue gets too big. We can either increase the queue-size in `RegisterChannel` or put the above call to `Send` in a go-routine.

### PR DESCRIPTION
**Pull request by ineiti**
Closes #219

### CODE REVIEW

File: treenode.go [hunk 1]
```diff
@@ -368,10 +378,16 @@ func (n *TreeNodeInstance) DispatchChannel(msgSlice []*ProtocolMsg) error {
...
 		for _, msg := range msgSlice {
-			out := n.channels[mt]
+			out := reflect.ValueOf(n.channels[mt])
 			m := n.reflectCreate(to.Elem(), msg)
 			log.Lvl4(n.Name(), "Dispatching msg type", mt, " to", to, " :", m.Field(1).Interface())
-			reflect.ValueOf(out).Send(m)
+			if out.Len() < out.Cap() {
+				out.Send(m)
+			} else {
+				return fmt.Errorf("channel too small for msg %s in %s: "+
```
Comment (nikkolasg) [inline treenode.go]: I would even panic in this case. What do you think ?

Comment (ineiti) [reply treenode.go]: that would mean that a rogue node could panic other nodes... I prefer not to panic there. Ideally it should stop the protocol, but I did not implement that.
