### PR TITLE
Maintenance

### LINKED ISSUE #186: monitor-race
Found the following in a travis-run. Putting mutex around `encoder`.

```
1 : (             platform.(*Localhost).Start: 146) - Starting 16 applications of /home/travis/gopath/src/github.com/dedis/cothority/example/simulation/build/ExampleHandlers
==================
WARNING: DATA RACE
Read at 0x000000cfc148 by goroutine 308:
  gopkg.in/dedis/onet.v1/simul/monitor.ConnectSink()
      /home/travis/gopath/src/gopkg.in/dedis/onet.v1/simul/monitor/measure.go:68 +0x55
  gopkg.in/dedis/onet.v1/simul/platform.(*Localhost).Start()
      /home/travis/gopath/src/gopkg.in/dedis/onet.v1/simul/platform/localhost.go:148 +0x598
  gopkg.in/dedis/onet.v1/simul.RunTest()
      /home/travis/gopath/src/gopkg.in/dedis/onet.v1/simul/build.go:196 +0x676
  gopkg.in/dedis/onet.v1/simul.RunTests()
      /home/travis/gopath/src/gopkg.in/dedis/onet.v1/simul/build.go:149 +0x3f3
  gopkg.in/dedis/onet.v1/simul.startBuild.func1()
      /home/travis/gopath/src/gopkg.in/dedis/onet.v1/simul/build.go:85 +0x64
Previous write at 0x000000cfc148 by goroutine 378:
  [failed to restore the stack]
Goroutine 308 (running) created at:
  gopkg.in/dedis/onet.v1/simul.startBuild()
      /home/travis/gopath/src/gopkg.in/dedis/onet.v1/simul/build.go:87 +0x9b4
  gopkg.in/dedis/onet.v1/simul.Start()
      /home/travis/gopath/src/gopkg.in/dedis/onet.v1/simul/simul.go:60 +0x433
  github.com/dedis/cothority/example/simulation.main()
      github.com/dedis/cothority/example/simulation/_test/_obj_test/simul.go:9 +0x61
  github.com/dedis/cothority/example/simulation.TestSimulation()
      /home/travis/gopath/src/github.com/dedis/cothority/example/simulation/simul_test.go:13 +0x254
  testing.tRunner()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/testing/testing.go:610 +0xc9
Goroutine 378 (finished) created at:
  gopkg.in/dedis/onet.v1/simul.RunTest()
      /home/travis/gopath/src/gopkg.in/dedis/onet.v1/simul/build.go:212 +0x792
  gopkg.in/dedis/onet.v1/simul.RunTests()
      /home/travis/gopath/src/gopkg.in/dedis/onet.v1/simul/build.go:149 +0x3f3
  gopkg.in/dedis/onet.v1/simul.startBuild.func1()
      /home/travis/gopath/src/gopkg.in/dedis/onet.v1/simul/build.go:85 +0x64
==================
```

### PR DESCRIPTION
**Pull request by ineiti**
created global struct for locking and removed EnableMeasure.
Closes #186

### CODE REVIEW

File: simul/monitor/measure.go [hunk 1]
```diff
@@ -65,18 +66,20 @@ type TimeMeasure struct {
 // encoder. It can be the address of a proxy or a monitoring process.
 // Returns an error if it could not connect to the endpoint.
 func ConnectSink(addr string) error {
-	if encoder != nil {
-		return nil
+	global.Lock()
+	defer global.Unlock()
+	if global.connection != nil {
+		return errors.New("Already connected")
```
Comment (nikkolasg) [inline simul/monitor/measure.go]: A more detailled error message would be nice.

**Comment by ineiti** [comment]
Yes, that's https://github.com/dedis/cothority/issues/284 - here I only wanted to add a lock, but couldn't resist to put the needed variables into a struct, and then remove an unused variable. Going down the rabbit-hole...
