### PR TITLE
Make it easier to debug when RunWait is set wrong

### LINKED ISSUE #323: onet simulation RunWait
With the change of having real `time.Duration` instead of `int`, `RunWait` and `ExperimentWait` in the `simulation.toml`-files don't behave as expected.

Need to change:
- either print an error if `RunWait` or `ExperimentWait` misses time-unit
- or suppose seconds if `RunWait` or `ExperimentWait` are integers

Files (at least):
simul/build.go
simul/platform/platform.go

### PR DESCRIPTION
**Pull request by jeffallen**
Also: Fix the type of RunWait for deterlab.

Fixes #323.

### CODE REVIEW

**Comment by ineiti** [comment]
There are three more places to take into account for, one for sure:
- `simul/README.md`
and two to decide:
- `simul/platform/mininet.go`
- `simul/platform/deterlab.go`

File: simul/build.go [hunk 1]
```diff
@@ -311,29 +318,42 @@ func getStartStop(rcs int) (int, int) {
...
+		return 0, err
 	}
+
+	// Otherwise calculate a useful default.
 	wait := 0 * time.Second
 	for _, rc := range rcs {
-		wait += getRunWait(rc)
+		w, err := getRunWait(rc)
+		if err != nil {
+			log.Fatal("RunWait:", err)
```
Comment (kc1212) [inline simul/build.go]: we can return an error here instand
