### PR TITLE
Count bytes more correctly

### LINKED ISSUE #292: tcp sendRaw does not call updateTx on short write
If sendRaw exits via handleError because c.conn.Write fails, then updateTx is not called.

### PR DESCRIPTION
**Pull request by jeffallen**
Count all the bytes, and also count them if there's an error.
Also: defer costs a memory allocation, don't use them when not needed.

Fixes #292.

### CODE REVIEW

File: network/router_test.go [hunk 1]
```diff
@@ -204,8 +205,10 @@ func testRouterAutoConnection(t *testing.T, fac routerFactory) {
 		t.Fatal("Should be able to stop h2")
 	}
 	err = h1.Send(h2.ServerIdentity, &SimpleMessage{12})
+	if err == nil {
+		t.Error("h1 let us send still")
+	}
 	require.NotNil(t, err)
```
Comment (ineiti) [inline network/router_test.go]: Why not
```
require.NotNil(t, err, "h1 let us send still")
```
?

Comment (jeffallen) [reply network/router_test.go]: It was left over from debugging. I do not like how require prints its errors, because Emacs cannot jump to the line. Can we just agree that sometimes calling t.Error(f) is ok?

Comment (ineiti) [reply network/router_test.go]: OK for me.
