### PR TITLE
[Network] #4 Fix small inconsistencies

### LINKED ISSUE #57: network.Receive return
Now: `network.Receive` returns a value
Wanted: `network.Receive` returns a pointer to `Envelope` like all other methods

### PR DESCRIPTION
**Pull request by nikkolasg**
This PR fixes some small inconsistencies or unused variables / methods.
+ Fixes #57 (returns pointer instead of value for Envelope)
+ Removes `RTypeToMessageTypeID`
+ Set `Marshal` and `Unmarshal` more visible in `encoding.go` 
+ Removes the `NewEnvelope` , `env.MarshalBinary()` and `env.Unmarshal`

### CODE REVIEW

File: network/encoding.go [hunk 1]
```diff
@@ -92,10 +92,56 @@ func MessageType(msg Message) MessageTypeID {
 	return msgType
 }
 
-// RTypeToMessageTypeID converts a reflect.Type to a MessageTypeID
-func RTypeToMessageTypeID(msg reflect.Type) MessageTypeID {
-	url := NamespaceBodyType + msg.String()
-	return MessageTypeID(uuid.NewV5(uuid.NamespaceURL, url))
+// Marshal marshals a struct with its respective type into a
```
Comment (ineiti) [inline network/encoding.go]: `Marshal outputs the type and the byte representation of a structure.`
