### PR TITLE
Warn when a failed connection might be from a known bug

### LINKED ISSUE #657: Make better error message for TLS 1.5 fix
The fix for go 1.15 with regard to TLS, #655, made the test-network crash. Some more information can be found in #656, which is, however, not capable of reproducing the error in a way that we can try to fix it.

So as the minimal service to users of our code, I propose we do the following:

Improve the error message given by an incompatible onet-connection and be more clear what _might_ have happened. E.g., something like:

```
TLS handshake failed - this might be due to mismatching go-version numbers, e.g., 1.14 and 1.15, between nodes. Another reason might be nodes running with onet (3.2.4) that cannot communicate with onet (3.2.5)
```

We should also consider removing the 3.2.5 tag and replacing it with a 3.3.0 tag, and write something in the CHANGELOG.md

### PR DESCRIPTION
**Pull request by jeffallen**
Fixes #657

### CODE REVIEW

**Review by ineiti — APPROVED** [review]

File: network/tcp.go [hunk 1]
```diff
@@ -284,7 +284,15 @@ func handleError(err error) error {
 		return ErrTimeout
 	}
 
-	log.Errorf("Unknown error caught: %s", err.Error())
+	if strings.Contains(err.Error(), "bad certificate") {
+		// This is a weak indication of the accidental
+		// onet 3.2.4/3.2.5 backwards incompatiblity, so explain
+		// the problem to help the user.
+		log.Errorf("Unknown error caught: %s %v", err.Error(),
+			"(This may be caused by Onet > v3.2.4 talking to Onet <= v3.2.4. See onet #657 for more info.)")
```
Comment (ineiti) [inline network/tcp.go:292]:
```suggestion
			"(This may be caused by Onet > v3.2.4 talking to Onet <= v3.2.4. See https://github.com/dedis/onet/issues/657 for more info.)")
```

**Review by ineiti — CHANGES_REQUESTED** [review]

**Comment by jeffallen** [comment]
The build failed due to a data race that seems to be associated with graceful:
```
WARNING: DATA RACE
314Read at 0x00c0001189f8 by goroutine 106:
315  net/http.(*conn).setState()
316      /home/travis/.gimme/versions/go1.15.linux.amd64/src/net/http/server.go:1753 +0x110
317  net/http.(*conn).serve.func1()
318      /home/travis/.gimme/versions/go1.15.linux.amd64/src/net/http/server.go:1806 +0xfd
319  net/http.(*conn).serve()
320      /home/travis/.gimme/versions/go1.15.linux.amd64/src/net/http/server.go:1945 +0xaff
321
322Previous write at 0x00c0001189f8 by goroutine 97:
323  gopkg.in/tylerb/graceful%2ev1.(*Server).manageConnections()
324      /home/travis/gopath/pkg/mod/gopkg.in/tylerb/graceful.v1@v1.2.15/graceful.go:399 +0x644
325
326Goroutine 106 (running) created at:
327  net/http.(*Server).Serve()
328      /home/travis/.gimme/versions/go1.15.linux.amd64/src/net/http/server.go:2969 +0x5d3
329  gopkg.in/tylerb/graceful%2ev1.(*Server).Serve()
330      /home/travis/gopath/pkg/mod/gopkg.in/tylerb/graceful.v1@v1.2.15/graceful.go:309 +0x472
331  gopkg.in/tylerb/graceful%2ev1.(*Server).ListenAndServe()
332      /home/travis/gopath/pkg/mod/gopkg.in/tylerb/graceful.v1@v1.2.15/graceful.go:147 +0xf2
333  go.dedis.ch/onet/v3.(*WebSocket).start.func1()
334      /home/travis/gopath/src/go.dedis.ch/onet/v3/websocket.go:194 +0x15c
335
336Goroutine 97 (finished) created at:
337  gopkg.in/tylerb/graceful%2ev1.(*Server).Serve()
338      /home/travis/gopath/pkg/mod/gopkg.in/tylerb/graceful.v1@v1.2.15/graceful.go:297 +0x377
339  gopkg.in/tylerb/graceful%2ev1.(*Server).ListenAndServe()
340      /home/travis/gopath/pkg/mod/gopkg.in/tylerb/graceful.v1@v1.2.15/graceful.go:147 +0xf2
341  go.dedis.ch/onet/v3.(*WebSocket).start.func1()
342      /home/travis/gopath/src/go.dedis.ch/onet/v3/websocket.go:194 +0x15c
343==================
344    testing.go:1023: race detected during execution of test
345--- FAIL: TestLocalTCPGenConnectableRoster (0.48s)
346=== CONT  
347    testing.go:1023: race detected during execution of test
348
```

We already have #601 reminding us to get rid of graceful, so I'm going to merge this anyway.
